PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE artisans_values (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, artisan_id INTEGER NOT NULL, field_name VARCHAR(64) NOT NULL, value CLOB NOT NULL);
COMMIT;
